import eventsImg1 from "../assets/homepage/events-1.jpg";

export async function fetchEvents() {
    return [
        {
            id: "1",
            title: "DigiCamp 2024: Strategic Digital and Community Organizing",
            category: "Kalikasan",
            date: "January 31, 2025",
            day: "Monday",
            time: "1:00 PM",
            location: "New Life Tondo",
            image_url: eventsImg1,
            about: "TARA, SAMAHAN KAMING LAKAYAN ANG DIGICAMP JOURNEY! What's up, mga kaT! Curious ba kayo kung ano ang ibig sabihin ng DigiCamp journey? Presenting you the 4 Phases of DIGICAMP 2024! Ang mga pangunahing aktibidad sa bawat isa sa 4 Phases ng mapagpalayang edukasyon ay nakapokus sa:  (1) Groundwork & Capacity Building, (2) Amplification, (3) Project Implementation, at (4) Evaluation at Network Learning.",
            speaker: "Eng. Zed",         
            starttime: "1:00 PM",
            endtime: "5:00 PM",
            going: "10"
        },
    
        {
            id: "2",
            title: "Lakas ng Bayan: Informative Webinar",
            category: "Kalusugan",
            date: "February 10, 2025",
            day: "Monday",
            time: "3:00 PM",
            location: "Tara Kabataan Haus",
            image_url: "src/assets/homepage/events-2.jpg",
            about: "Aqweqwegqaweqawheqwagehqawiuegyaqgeuioaqweghqawioegyaqweuigoqwayegoiuaqwyegqawiougeyqwiougeyqawo"
        },
        {
            id: "3",
            title: "Eco Summit 2024: Sustainable Communities",
            category: "Kalikasan",
            date: "March 5, 2025",
            day: "Monday",
            time: "10:00 AM",
            location: "Green Planet Hall",
            image_url: "src/assets/homepage/events-3.jpg"
        },
        {
            id: "4",
            title: "DigiCamp 2024: Strategic Digital and Community Organizing",
            category: "Kalikasan",
            date: "January 31, 2025",
            day: "Monday",
            time: "1:00 PM",
            location: "Tara Kabataan Haus",
            image_url: "src/assets/homepage/events-1.jpg"
            
        },
        {
            id: "1",
            title: "DigiCamp 2024: Strategic Digital and Community Organizing",
            category: "Kalikasan",
            date: "January 31, 2025",
            day: "Monday",
            time: "1:00 PM",
            location: "New Life Tondo",
            image_url: "./src/assets/homepage/events-1.jpg",
            about: "TARA, SAMAHAN KAMING LAKAYAN ANG DIGICAMP JOURNEY! What's up, mga kaT! Curious ba kayo kung ano ang ibig sabihin ng DigiCamp journey? Presenting you the 4 Phases of DIGICAMP 2024! Ang mga pangunahing aktibidad sa bawat isa sa 4 Phases ng mapagpalayang edukasyon ay nakapokus sa:  (1) Groundwork & Capacity Building, (2) Amplification, (3) Project Implementation, at (4) Evaluation at Network Learning.",
            speaker: "Eng. Zed",         
            starttime: "1:00 PM",
            endtime: "5:00 PM",
            going: "10"
        },
        {
            id: "1",
            title: "DigiCamp 2024: Strategic Digital and Community Organizing",
            category: "Kalikasan",
            date: "January 31, 2025",
            day: "Monday",
            time: "1:00 PM",
            location: "New Life Tondo",
            image_url: "./src/assets/homepage/events-1.jpg",
            about: "TARA, SAMAHAN KAMING LAKAYAN ANG DIGICAMP JOURNEY! What's up, mga kaT! Curious ba kayo kung ano ang ibig sabihin ng DigiCamp journey? Presenting you the 4 Phases of DIGICAMP 2024! Ang mga pangunahing aktibidad sa bawat isa sa 4 Phases ng mapagpalayang edukasyon ay nakapokus sa:  (1) Groundwork & Capacity Building, (2) Amplification, (3) Project Implementation, at (4) Evaluation at Network Learning.",
            speaker: "Eng. Zed",         
            starttime: "1:00 PM",
            endtime: "5:00 PM",
            going: "10"
        },
        {
            id: "1",
            title: "DigiCamp 2024: Strategic Digital and Community Organizing",
            category: "Kalikasan",
            date: "January 31, 2025",
            day: "Monday",
            time: "1:00 PM",
            location: "New Life Tondo",
            image_url: "./src/assets/homepage/events-1.jpg",
            about: "TARA, SAMAHAN KAMING LAKAYAN ANG DIGICAMP JOURNEY! What's up, mga kaT! Curious ba kayo kung ano ang ibig sabihin ng DigiCamp journey? Presenting you the 4 Phases of DIGICAMP 2024! Ang mga pangunahing aktibidad sa bawat isa sa 4 Phases ng mapagpalayang edukasyon ay nakapokus sa:  (1) Groundwork & Capacity Building, (2) Amplification, (3) Project Implementation, at (4) Evaluation at Network Learning.",
            speaker: "Eng. Zed",         
            starttime: "1:00 PM",
            endtime: "5:00 PM",
            going: "10"
        },
        {
            id: "1",
            title: "DigiCamp 2024: Strategic Digital and Community Organizing",
            category: "Kalikasan",
            date: "January 31, 2025",
            day: "Monday",
            time: "1:00 PM",
            location: "New Life Tondo",
            image_url: "./src/assets/homepage/events-1.jpg",
            about: "TARA, SAMAHAN KAMING LAKAYAN ANG DIGICAMP JOURNEY! What's up, mga kaT! Curious ba kayo kung ano ang ibig sabihin ng DigiCamp journey? Presenting you the 4 Phases of DIGICAMP 2024! Ang mga pangunahing aktibidad sa bawat isa sa 4 Phases ng mapagpalayang edukasyon ay nakapokus sa:  (1) Groundwork & Capacity Building, (2) Amplification, (3) Project Implementation, at (4) Evaluation at Network Learning.",
            speaker: "Eng. Zed",         
            starttime: "1:00 PM",
            endtime: "5:00 PM",
            going: "10"
        },
        {
            id: "1",
            title: "DigiCamp 2024: Strategic Digital and Community Organizing",
            category: "Kalikasan",
            date: "January 31, 2025",
            day: "Monday",
            time: "1:00 PM",
            location: "New Life Tondo",
            image_url: "./src/assets/homepage/events-1.jpg",
            about: "TARA, SAMAHAN KAMING LAKAYAN ANG DIGICAMP JOURNEY! What's up, mga kaT! Curious ba kayo kung ano ang ibig sabihin ng DigiCamp journey? Presenting you the 4 Phases of DIGICAMP 2024! Ang mga pangunahing aktibidad sa bawat isa sa 4 Phases ng mapagpalayang edukasyon ay nakapokus sa:  (1) Groundwork & Capacity Building, (2) Amplification, (3) Project Implementation, at (4) Evaluation at Network Learning.",
            speaker: "Eng. Zed",         
            starttime: "1:00 PM",
            endtime: "5:00 PM",
            going: "10"
        },
        {
            id: "1",
            title: "DigiCamp 2024: Strategic Digital and Community Organizing",
            category: "Kalikasan",
            date: "January 31, 2025",
            day: "Monday",
            time: "1:00 PM",
            location: "New Life Tondo",
            image_url: "./src/assets/homepage/events-1.jpg",
            about: "TARA, SAMAHAN KAMING LAKAYAN ANG DIGICAMP JOURNEY! What's up, mga kaT! Curious ba kayo kung ano ang ibig sabihin ng DigiCamp journey? Presenting you the 4 Phases of DIGICAMP 2024! Ang mga pangunahing aktibidad sa bawat isa sa 4 Phases ng mapagpalayang edukasyon ay nakapokus sa:  (1) Groundwork & Capacity Building, (2) Amplification, (3) Project Implementation, at (4) Evaluation at Network Learning.",
            speaker: "Eng. Zed",         
            starttime: "1:00 PM",
            endtime: "5:00 PM",
            going: "10"
        },
        {
            id: "1",
            title: "DigiCamp 2024: Strategic Digital and Community Organizing",
            category: "Kalikasan",
            date: "January 31, 2025",
            day: "Monday",
            time: "1:00 PM",
            location: "New Life Tondo",
            image_url: "./src/assets/homepage/events-1.jpg",
            about: "TARA, SAMAHAN KAMING LAKAYAN ANG DIGICAMP JOURNEY! What's up, mga kaT! Curious ba kayo kung ano ang ibig sabihin ng DigiCamp journey? Presenting you the 4 Phases of DIGICAMP 2024! Ang mga pangunahing aktibidad sa bawat isa sa 4 Phases ng mapagpalayang edukasyon ay nakapokus sa:  (1) Groundwork & Capacity Building, (2) Amplification, (3) Project Implementation, at (4) Evaluation at Network Learning.",
            speaker: "Eng. Zed",         
            starttime: "1:00 PM",
            endtime: "5:00 PM",
            going: "10"
        },
        {
            id: "1",
            title: "DigiCamp 2024: Strategic Digital and Community Organizing",
            category: "Kalikasan",
            date: "January 31, 2025",
            day: "Monday",
            time: "1:00 PM",
            location: "New Life Tondo",
            image_url: "./src/assets/homepage/events-1.jpg",
            about: "TARA, SAMAHAN KAMING LAKAYAN ANG DIGICAMP JOURNEY! What's up, mga kaT! Curious ba kayo kung ano ang ibig sabihin ng DigiCamp journey? Presenting you the 4 Phases of DIGICAMP 2024! Ang mga pangunahing aktibidad sa bawat isa sa 4 Phases ng mapagpalayang edukasyon ay nakapokus sa:  (1) Groundwork & Capacity Building, (2) Amplification, (3) Project Implementation, at (4) Evaluation at Network Learning.",
            speaker: "Eng. Zed",         
            starttime: "1:00 PM",
            endtime: "5:00 PM",
            going: "10"
        },
        {
            id: "1",
            title: "DigiCamp 2024: Strategic Digital and Community Organizing",
            category: "Kalikasan",
            date: "January 31, 2025",
            day: "Monday",
            time: "1:00 PM",
            location: "New Life Tondo",
            image_url: "./src/assets/homepage/events-1.jpg",
            about: "TARA, SAMAHAN KAMING LAKAYAN ANG DIGICAMP JOURNEY! What's up, mga kaT! Curious ba kayo kung ano ang ibig sabihin ng DigiCamp journey? Presenting you the 4 Phases of DIGICAMP 2024! Ang mga pangunahing aktibidad sa bawat isa sa 4 Phases ng mapagpalayang edukasyon ay nakapokus sa:  (1) Groundwork & Capacity Building, (2) Amplification, (3) Project Implementation, at (4) Evaluation at Network Learning.",
            speaker: "Eng. Zed",         
            starttime: "1:00 PM",
            endtime: "5:00 PM",
            going: "10"
        },
        {
            id: "1",
            title: "DigiCamp 2024: Strategic Digital and Community Organizing",
            category: "Kalikasan",
            date: "January 31, 2025",
            day: "Monday",
            time: "1:00 PM",
            location: "New Life Tondo",
            image_url: "./src/assets/homepage/events-1.jpg",
            about: "TARA, SAMAHAN KAMING LAKAYAN ANG DIGICAMP JOURNEY! What's up, mga kaT! Curious ba kayo kung ano ang ibig sabihin ng DigiCamp journey? Presenting you the 4 Phases of DIGICAMP 2024! Ang mga pangunahing aktibidad sa bawat isa sa 4 Phases ng mapagpalayang edukasyon ay nakapokus sa:  (1) Groundwork & Capacity Building, (2) Amplification, (3) Project Implementation, at (4) Evaluation at Network Learning.",
            speaker: "Eng. Zed",         
            starttime: "1:00 PM",
            endtime: "5:00 PM",
            going: "10"
        },
        {
            id: "1",
            title: "DigiCamp 2024: Strategic Digital and Community Organizing",
            category: "Kalikasan",
            date: "January 31, 2025",
            day: "Monday",
            time: "1:00 PM",
            location: "New Life Tondo",
            image_url: "./src/assets/homepage/events-1.jpg",
            about: "TARA, SAMAHAN KAMING LAKAYAN ANG DIGICAMP JOURNEY! What's up, mga kaT! Curious ba kayo kung ano ang ibig sabihin ng DigiCamp journey? Presenting you the 4 Phases of DIGICAMP 2024! Ang mga pangunahing aktibidad sa bawat isa sa 4 Phases ng mapagpalayang edukasyon ay nakapokus sa:  (1) Groundwork & Capacity Building, (2) Amplification, (3) Project Implementation, at (4) Evaluation at Network Learning.",
            speaker: "Eng. Zed",         
            starttime: "1:00 PM",
            endtime: "5:00 PM",
            going: "10"
        },

        // {
        //     id: 5,
        //     title: "Lakas ng Bayan: Informative Webinar",
        //     category: "Kalusugan",
        //     date: "February 10, 2025",
        //     time: "3:00 PM",
        //     location: "Tara Kabataan Haus",
        //     image_url: "src/assets/homepage/events-2.jpg"
        // },
        // {
        //     id: 6,
        //     title: "Eco Summit 2024: Sustainable Communities",
        //     category: "Kalikasan",
        //     date: "March 5, 2025",
        //     time: "10:00 AM",
        //     location: "Green Planet Hall",
        //     image_url: "src/assets/homepage/events-3.jpg"
        // }
    ];
}
